In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


# Checking numpy version

In [5]:
print(np.__version__)

1.26.4


# 3-D Array

In [7]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Checking number of dimensions

In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

## Create an array with 5 dimensions and verify that it has 5 dimensions:

In [15]:
arrND = np.array([1,2,3,4], ndmin=5)

print(arrND)
print("No of dimensions in array is: " , arrND.ndim)

[[[[[1 2 3 4]]]]]
No of dimensions in array is:  5


# Access array elements

In [17]:
arr=np.array([1,2,3,4])

print(arr[1])

print(arr[0] + arr[2])

2
4


# Access 2-D arrays

In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("2nd element on 1st row is: " , arr[0,1])
print("5th element on 2nd row is: " , arr[1,4])

2nd element on 1st row is:  2
5th element on 2nd row is:  10


# Access 3-D arrays

In [20]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


### Example Explained 

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6


# Negative Indexing

In [21]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Last element from 2nd dimension: " , arr[1,-1])

Last element from 2nd dimension:  10


# slicing 2-D arrays

In [24]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


## From both elements, return index 2:

In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [28]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]
