In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


# Checking numpy version

In [4]:
print(np.__version__)

1.26.4


# 3-D Array

In [5]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Checking number of dimensions

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

## Create an array with 5 dimensions and verify that it has 5 dimensions:

In [7]:
arrND = np.array([1,2,3,4], ndmin=5)

print(arrND)
print("No of dimensions in array is: " , arrND.ndim)

[[[[[1 2 3 4]]]]]
No of dimensions in array is:  5


# Access array elements

In [8]:
arr=np.array([1,2,3,4])

print(arr[1])

print(arr[0] + arr[2])

2
4


# Access 2-D arrays

In [9]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("2nd element on 1st row is: " , arr[0,1])
print("5th element on 2nd row is: " , arr[1,4])

2nd element on 1st row is:  2
5th element on 2nd row is:  10


# Access 3-D arrays

In [10]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


### Example Explained 

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6


# Negative Indexing

In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Last element from 2nd dimension: " , arr[1,-1])

Last element from 2nd dimension:  10


# slicing 2-D arrays

In [12]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


## From both elements, return index 2:

In [13]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Checking the datatype of an array

In [15]:
arr = np.array([1,2,3,4])

print(arr.dtype)

int32


In [16]:
arr = np.array(["rolce royce","mercedes","GTR"])

print(arr.dtype)

<U11


## We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

i - integer \
b - boolean \
u - unsigned integer \
f - float \
c - complex float \
m - timedelta \
M - datetime \
O - object \
S - string \
U - unicode string \
V - fixed chunk of memory for other type ( void )

In [17]:
arr = np.array([1,2,3,4] , dtype = 'S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## For i, u, f, S and U we can define size as well.

In [18]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [19]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# Converting datatype to an existing array

### The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

 The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

 The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [21]:
arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [22]:
arr = np.array([1.1,2.1,3.1])

newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Copy vs View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [24]:
# COPY

arr = np.array([1,2,3,4,5])
x= arr.copy()
x[0] = 10

print(arr)
print(x)

[1 2 3 4 5]
[10  2  3  4  5]


In [25]:
# VIEW

arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 10

print(arr)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]


In [26]:
# VIEW - changes in original array also gets changed in view

arr = np.array([1,2,3,4,5])
x= arr.view()
arr[0] = 10

print(arr)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]


# Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.


In [27]:
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Shape of an Array
The shape of an array is the number of elements in each dimension.

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


### The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [30]:
arr = np.array([1,2,3,4] , ndmin = 5)
print(arr)
print("Shape of array is: " , arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array is:  (1, 1, 1, 1, 4)


# What does the shape tuple represent?
Integers at every index tells about the number of elements the corresponding dimension has.

In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

# 🌟 Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Reshape From 1-D to 2-D
Example\

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

Example


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ⭕ Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

# Check if the returned array is a copy or a view:

In [33]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(4,2)
print(newarr.base)

[1 2 3 4 5 6 7 8]


## The example above returns the original array, so it is a view.

# Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [34]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### **Note**: We can not pass -1 to more than one dimension.

# 🌟 Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### ⭕ Note : There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

# Iterating arrays

In [37]:
# 2-D array

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [40]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [41]:
# 3-D arrays

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [42]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# 🌟 Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [43]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# 🌟 Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [44]:
arr = np.array([1,2,3])

for x in np.nditer(arr,flags=["buffered"],op_dtypes="S"):
    print(x)

b'1'
b'2'
b'3'


# 🌟 Iterating With Different Step Size
We can use filtering and followed by iteration.

In [46]:
arr = np.array([[1,2,3],[4,5,6]])

for x in np.nditer(arr[:,::2]):
    print(x)

1
3
4
6


# 🌟 Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [47]:
arr = np.array([1,2,3,4,5,6])

for idx , x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


In [48]:
# 2-D array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
