In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


# Checking numpy version

In [4]:
print(np.__version__)

1.26.4


# 3-D Array

In [5]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Checking number of dimensions

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

## Create an array with 5 dimensions and verify that it has 5 dimensions:

In [7]:
arrND = np.array([1,2,3,4], ndmin=5)

print(arrND)
print("No of dimensions in array is: " , arrND.ndim)

[[[[[1 2 3 4]]]]]
No of dimensions in array is:  5


# Access array elements

In [8]:
arr=np.array([1,2,3,4])

print(arr[1])

print(arr[0] + arr[2])

2
4


# Access 2-D arrays

In [9]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("2nd element on 1st row is: " , arr[0,1])
print("5th element on 2nd row is: " , arr[1,4])

2nd element on 1st row is:  2
5th element on 2nd row is:  10


# Access 3-D arrays

In [10]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


### Example Explained 

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6


# Negative Indexing

In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Last element from 2nd dimension: " , arr[1,-1])

Last element from 2nd dimension:  10


# slicing 2-D arrays

In [12]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


## From both elements, return index 2:

In [13]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Checking the datatype of an array

In [15]:
arr = np.array([1,2,3,4])

print(arr.dtype)

int32


In [16]:
arr = np.array(["rolce royce","mercedes","GTR"])

print(arr.dtype)

<U11


## We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

i - integer \
b - boolean \
u - unsigned integer \
f - float \
c - complex float \
m - timedelta \
M - datetime \
O - object \
S - string \
U - unicode string \
V - fixed chunk of memory for other type ( void )

In [17]:
arr = np.array([1,2,3,4] , dtype = 'S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## For i, u, f, S and U we can define size as well.

In [18]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [19]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# Converting datatype to an existing array

### The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

 The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

 The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [20]:
arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [21]:
arr = np.array([1.1,2.1,3.1])

newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Copy vs View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [22]:
# COPY

arr = np.array([1,2,3,4,5])
x= arr.copy()
x[0] = 10

print(arr)
print(x)

[1 2 3 4 5]
[10  2  3  4  5]


In [23]:
# VIEW

arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 10

print(arr)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]


In [24]:
# VIEW - changes in original array also gets changed in view

arr = np.array([1,2,3,4,5])
x= arr.view()
arr[0] = 10

print(arr)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]


# Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.


In [25]:
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Shape of an Array
The shape of an array is the number of elements in each dimension.

In [26]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


### The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [27]:
arr = np.array([1,2,3,4] , ndmin = 5)
print(arr)
print("Shape of array is: " , arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array is:  (1, 1, 1, 1, 4)


# What does the shape tuple represent?
Integers at every index tells about the number of elements the corresponding dimension has.

In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

# 🌟 Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Reshape From 1-D to 2-D
Example\

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

Example


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ⭕ Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

# Check if the returned array is a copy or a view:

In [30]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(4,2)
print(newarr.base)

[1 2 3 4 5 6 7 8]


## The example above returns the original array, so it is a view.

# Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [31]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### **Note**: We can not pass -1 to more than one dimension.

# 🌟 Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### ⭕ Note : There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

# Iterating arrays

In [33]:
# 2-D array

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [34]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [35]:
# 3-D arrays

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [36]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# 🌟 Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [37]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# 🌟 Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [38]:
arr = np.array([1,2,3])

for x in np.nditer(arr,flags=["buffered"],op_dtypes="S"):
    print(x)

b'1'
b'2'
b'3'


# 🌟 Iterating With Different Step Size
We can use filtering and followed by iteration.

In [39]:
arr = np.array([[1,2,3],[4,5,6]])

for x in np.nditer(arr[:,::2]):
    print(x)

1
3
4
6


# 🌟 Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [40]:
arr = np.array([1,2,3,4,5,6])

for idx , x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


In [41]:
# 2-D array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [48]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [44]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2) , axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [46]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2) , axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2) , axis=-1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [50]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


# Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [52]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.hstack((arr1,arr2))
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [53]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.vstack((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [54]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.dstack((arr1,arr2))
print(arr)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


# Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [56]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)
print(newarr)

# The return value is a list containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [57]:
# If the array has less elements than required, it will adjust from the end accordingly.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

# Split Into Arrays
The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [58]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [59]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])

newarr = np.array_split(arr,2)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


## In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the row (axis=1).

In [60]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

newarr = np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [61]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

newarr = np.array_split(arr,2,axis=1)
print(newarr)

[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [63]:
# An alternate solution is using hsplit() opposite of hstack()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
newarr = np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

# 🌟 Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [64]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


# ⭕ Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

- The searchsorted() method is assumed to be used on sorted arrays.

In [66]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr,7)
print(x)

1


## Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [67]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr,7,side='right')
print(x)
                    

2


# Multiple Values
To search for more than one value, use an array with the specified values.

In [68]:
# Find the indexes where the values 2, 4, and 6 should be inserted:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


#### The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

# Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [70]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
# This method returns a copy of the array, leaving the original array unchanged.

[0 1 2 3]


In [71]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [72]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


## Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [73]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# 🌟 Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [74]:
# Create an array from the elements on index 0 and 2:

arr = np.array([41,42,43,44])

x = [True,False,True,False]

newarr = arr[x]
print(newarr)

[41 43]


## Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [77]:
# Create a filter array that will return only values higher than 42:

arr = np.array([40,41,42,43,44,45])

filter_arr = []

for x in arr:

    if x>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, False, True, True, True]
[43 44 45]


# 🌟🌟🌟 Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [79]:
arr = np.array([40,41,42,43,44,45])

filter_arr = arr>42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False False  True  True  True]
[43 44 45]
